title: Lalit Mahale
description: Lalit Mahale's Personal Website
baseurl: ""

username:Lalit Mahale
typing_text: AI Engineer / NLP Engineer / Data Scientist / ML Eegieer

email: lalitmahale121@gmail.com
telegram_username: that_one_martian
linkedin_username: https://www.linkedin.com/in/lalitmahale1997/
github_username: LalitMahale
facebook_username: 
viber_number: 8087830153

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://drive.google.com/file/d/1qeBuJLUDnrkYs4SglcZoibFnbjU24-hx/view

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: daweedkob/daweedkob.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - daweedkob.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - daweedkob

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
